### ISSUE TITLE
Package not working for android devices

### ISSUE THREAD

**Issue by saurabh2k26** [alexschwantes/testcafe-browser-provider-selenium#14]
I am trying to run testcafe tests on android chrome.

This is my docker-compose.yml
```
version: "3"
services:
 hub:
   image: selenium/hub
   container_name: hub
   ports:
     - "4444:4444"
 samsung_galaxy:
   image: butomo1989/docker-android-x86-8.1
   privileged: true
   links:
     - hub
   depends_on:
     - hub
   ports:
     - "6080:6080"
   environment:
     - DEVICE=Samsung Galaxy S6
     - CONNECT_TO_GRID=True
     - APPIUM=true
     - SELENIUM_HOST=hub
     - MOBILE_WEB_TEST=False
     - AUTO_RECORD=True
```

After doing docker-compose up, i can see device in http://0.0.0.0:4444/grid/console
<img width="948" alt="Screenshot 2020-06-03 at 9 56 13 PM" src="https://user-images.githubusercontent.com/5627527/83662555-4449c300-a5e5-11ea-8e2c-896408397d47.png">

Now when i try to run my tests, i get error:
```
[my_first_project (master)]$ testcafe selenium:chrome:android my_first_test.js 
Using locally installed version of TestCafe.
The "src", "browsers" options from the configuration file will be ignored.
ERROR Was unable to open the browser "selenium:chrome:android" due to error.

WebDriverError: Error forwarding the new session cannot find : Capabilities {browserName: chrome, platformName: android}
    at Object.checkLegacyResponse (/Users/xxx/node_modules/selenium-webdriver/lib/error.js:585:15)
    at parseHttpResponse (/Users/xxx/node_modules/selenium-webdriver/lib/http.js:556:13)
    at Executor.execute (/Users/xxx/node_modules/selenium-webdriver/lib/http.js:491:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Type "testcafe -h" for help.
```
